/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class emuProcess */

#ifndef _Included_emuProcess
#define _Included_emuProcess
#ifdef __cplusplus
extern "C" {
#endif
#undef emuProcess_emulatorPort
#define emuProcess_emulatorPort 4445L
/*
 * Class:     emuProcess
 * Method:    setBufferNull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_emuProcess_setBufferNull
  (JNIEnv *, jclass);

/*
 * Class:     emuProcess
 * Method:    returnReg
 * Signature: ()LRegFile;
 */
JNIEXPORT jobject JNICALL Java_emuProcess_returnReg
  (JNIEnv *, jclass);

/*
 * Class:     emuProcess
 * Method:    returnPC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_emuProcess_returnPC
  (JNIEnv *, jclass);

/*
 * Class:     emuProcess
 * Method:    secondMain
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_emuProcess_secondMain
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     emuProcess
 * Method:    executeOneInstruction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_emuProcess_executeOneInstruction
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
