#line 2 "dynamic/tools/sledscanner.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /net/claque.eng/export/home3/walkabout/CVS/dynamic/CVSROOT/dynamic/tools/sledscanner.cc,v 1.9 2002/01/09 23:25:29 cristina Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
static yyconst short int yy_accept[276] =
    {   0,
        0,    0,   81,   79,   77,   78,    1,   23,   79,    2,
        3,    4,    5,    6,    7,    8,    9,   10,   11,   72,
       12,   73,   73,   13,   14,   15,   17,   16,   21,   72,
       22,   24,   25,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   18,   19,   20,   27,    0,   75,    0,   71,   72,
       72,   76,   73,    0,   26,   29,   30,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       48,   72,   72,   72,   52,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   64,   72,   72,   72,   72,

       72,   28,   74,   72,   32,   72,   34,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   46,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   40,   72,   72,   72,   72,
       49,   50,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   61,   72,   72,   65,   72,   72,   68,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   42,   43,
       72,   51,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   67,   69,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   45,   72,   53,   72,   72,
       72,   72,   72,   72,   72,   62,   63,   72,   72,   31,
       72,   35,   36,   72,   72,   39,   41,   72,   72,   54,
       72,   72,   72,   72,   72,   72,   72,   72,   33,   72,
       72,   72,   72,   72,   56,   72,   72,   72,   72,   72,
       70,   37,   72,   44,   72,   55,   72,   72,   72,   72,
       66,   72,   47,   72,   72,   72,   72,   72,   72,   58,
       59,   60,   38,   57,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   27,   27,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       29,    1,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   28,   42,   43,   44,   45,
       46,   47,   28,   48,   49,   50,   51,   28,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    3,
        2,    1,    1,    1,    1,    1,    3,    2,    1,    1,
        1,    2,    3,    3,    3,    3,    3,    3,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst short int yy_base[280] =
    {   0,
        0,    0,  519,  520,  520,  520,  494,  512,  513,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,   42,
      520,   41,   45,  520,  520,  491,  489,  489,  520,  491,
      520,  520,  520,   41,   46,   45,   47,   49,   52,   48,
       51,   58,   55,   50,   59,   81,   82,   84,   61,   63,
       83,  520,  520,  520,  520,  506,  505,  506,  520,   57,
      487,  520,   91,    0,  520,  520,  520,   92,   96,   97,
       99,  100,  111,  112,  113,  114,  101,  105,  118,  115,
      486,  106,  119,  120,  485,  123,  131,  124,  138,  132,
      126,  136,  146,  151,  152,  484,  155,  156,  157,  158,

      159,  483,    0,  160,  482,  164,  481,  161,  162,  165,
      166,  168,  167,  173,  171,  179,  480,  172,  184,  188,
      189,  190,  195,  196,  197,  198,  200,  202,  206,  203,
      204,  207,  208,  213,  209,  211,  220,  223,  221,  216,
      225,  218,  229,  240,  243,  479,  242,  244,  245,  247,
      478,  477,  248,  250,  249,  251,  252,  253,  256,  257,
      262,  476,  258,  267,  475,  273,  266,  474,  274,  270,
      275,  281,  280,  283,  285,  287,  288,  291,  473,  290,
      295,  472,  292,  297,  299,  300,  302,  301,  305,  306,
      312,  304,  311,  471,  470,  313,  324,  326,  329,  331,

      334,  332,  338,  337,  339,  469,  335,  468,  340,  345,
      342,  341,  343,  346,  347,  467,  466,  351,  349,  454,
      354,  453,  452,  356,  357,  451,  448,  360,  358,  446,
      369,  373,  378,  376,  379,  381,  384,  386,  445,  382,
      385,  388,  390,  392,  444,  394,  403,  396,  393,  404,
      443,  442,  399,  440,  410,  437,  412,  415,  416,  417,
      436,  420,  435,  421,  422,  423,  426,  428,  429,  434,
      433,  430,  427,   60,  520,  478,  481,  483,   72
    } ;

static yyconst short int yy_def[280] =
    {   0,
      275,    1,  275,  275,  275,  275,  275,  276,  277,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  278,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  278,
      275,  275,  275,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  275,  275,  275,  275,  276,  275,  277,  275,  278,
      278,  275,  275,  279,  275,  275,  275,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  279,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,    0,  275,  275,  275,  275
    } ;

static yyconst short int yy_nxt[579] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   31,   32,
       33,   30,   34,   35,   36,   37,   38,   39,   40,   30,
       41,   42,   30,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   30,   30,   30,   52,   53,   54,   60,   63,
       63,   62,   62,   63,   63,   62,   62,   62,   62,   62,
       62,   62,   62,  102,  103,   62,   68,   62,   62,   62,
       62,   62,   84,   62,   72,   69,   71,   74,   77,   70,
       73,   75,   78,   64,   82,   76,   85,   79,   80,   81,

       83,   62,   62,   62,   62,   86,   96,   98,   87,   63,
       63,   99,   62,   88,   97,   89,   62,   62,   91,   62,
       62,   62,  100,   90,   92,   62,   62,  104,  101,   93,
       94,   62,   62,   62,   62,   62,  108,   95,   62,   62,
       62,  116,  119,   62,   62,  106,   62,  118,  107,  105,
      115,   62,   62,  109,  110,  111,   62,  122,   62,  123,
      112,  113,  114,  121,  127,  117,   62,  120,  128,  126,
      124,   62,   62,  125,  129,   62,   62,   62,   62,   62,
       62,   62,   62,  131,   62,   62,   62,   62,   62,  130,
      134,   62,   62,   62,  136,  141,  132,  135,  137,   62,

      140,  133,  145,  146,   62,  148,  138,  139,   62,   62,
       62,  143,  142,  147,  144,   62,   62,   62,   62,  150,
       62,  149,   62,   62,   62,  153,   62,   62,   62,   62,
      151,   62,  156,   62,  159,  154,   62,  152,   62,  162,
       62,   62,  155,   62,  165,   62,  157,  160,  158,   62,
      161,  163,  166,  167,  169,  168,  164,  171,  170,  172,
       62,  174,   62,   62,   62,   62,  173,   62,   62,   62,
       62,   62,   62,   62,  175,  177,   62,   62,   62,  181,
      180,  184,   62,  179,  178,  183,   62,   62,  186,  176,
       62,  189,  188,   62,   62,   62,  182,  187,  185,  192,

       62,   62,  190,   62,  194,   62,  191,   62,   62,  193,
       62,   62,   62,  195,  198,   62,  199,   62,  196,   62,
       62,   62,   62,  197,   62,   62,   62,  200,  208,  201,
      205,   62,   62,   62,  202,  203,  204,  214,  206,  207,
      213,  209,  212,  215,   62,  218,   62,  211,  216,   62,
      210,   62,   62,  219,   62,   62,  217,   62,   62,   62,
       62,   62,   62,   62,  222,   62,   62,   62,  221,   62,
      224,   62,  220,  226,   62,  230,   62,   62,   62,  223,
       62,  227,  225,  228,  229,  231,  232,  236,  234,   62,
      233,  241,  237,   62,  243,  235,   62,  242,   62,   62,

      240,   62,   62,  238,   62,   62,   62,  239,   62,  246,
       62,  248,   62,   62,   62,  249,   62,  244,  247,   62,
      250,  245,  251,   62,   62,  260,  255,  257,  256,  259,
       62,  252,   62,  254,  253,   62,   62,   62,  258,  261,
       62,   62,   62,   62,  262,  263,   62,   62,   62,   62,
       62,  265,  264,   62,   62,   62,   62,   62,  266,  271,
       62,  267,   62,   62,   62,   62,   62,  268,   62,  270,
      269,   62,   62,   62,   62,  272,  273,  274,   56,   56,
       56,   58,   58,   58,   61,   61,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   59,   56,
       57,   62,   67,   66,   65,   59,   57,   55,  275,    3,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275
    } ;

static yyconst short int yy_chk[579] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   20,   22,
       22,   34,   20,   23,   23,   36,   35,   37,   40,   38,
       44,   41,   39,   60,  279,   43,   34,   60,   42,   45,
      274,   49,   44,   50,   36,   34,   35,   37,   39,   34,
       36,   38,   39,   22,   42,   38,   45,   39,   40,   41,

       43,   46,   47,   51,   48,   45,   49,   50,   45,   63,
       63,   50,   68,   46,   49,   46,   69,   70,   47,   71,
       72,   77,   51,   46,   48,   78,   82,   68,   51,   48,
       48,   73,   74,   75,   76,   80,   72,   48,   79,   83,
       84,   78,   82,   86,   88,   70,   91,   80,   71,   69,
       77,   87,   90,   73,   73,   73,   92,   86,   89,   86,
       74,   75,   76,   84,   90,   79,   93,   83,   91,   89,
       87,   94,   95,   88,   92,   97,   98,   99,  100,  101,
      104,  108,  109,   94,  106,  110,  111,  113,  112,   93,
       98,  115,  118,  114,  100,  108,   95,   99,  100,  116,

      106,   97,  112,  113,  119,  115,  101,  104,  120,  121,
      122,  110,  109,  114,  111,  123,  124,  125,  126,  118,
      127,  116,  128,  130,  131,  121,  129,  132,  133,  135,
      119,  136,  124,  134,  127,  122,  140,  120,  142,  130,
      137,  139,  123,  138,  133,  141,  125,  128,  126,  143,
      129,  131,  134,  135,  137,  136,  132,  139,  138,  140,
      144,  142,  147,  145,  148,  149,  141,  150,  153,  155,
      154,  156,  157,  158,  143,  145,  159,  160,  163,  150,
      149,  155,  161,  148,  147,  154,  167,  164,  157,  144,
      170,  160,  159,  166,  169,  171,  153,  158,  156,  164,

      173,  172,  161,  174,  167,  175,  163,  176,  177,  166,
      180,  178,  183,  169,  172,  181,  173,  184,  170,  185,
      186,  188,  187,  171,  192,  189,  190,  174,  183,  175,
      180,  193,  191,  196,  176,  177,  178,  189,  180,  181,
      188,  184,  187,  190,  197,  193,  198,  186,  191,  199,
      185,  200,  202,  196,  201,  207,  192,  204,  203,  205,
      209,  212,  211,  213,  199,  210,  214,  215,  198,  219,
      201,  218,  197,  203,  221,  209,  224,  225,  229,  200,
      228,  204,  202,  205,  207,  210,  211,  215,  213,  231,
      212,  225,  218,  232,  229,  214,  234,  228,  233,  235,

      224,  236,  240,  219,  237,  241,  238,  221,  242,  233,
      243,  235,  244,  249,  246,  236,  248,  231,  234,  253,
      237,  232,  238,  247,  250,  249,  243,  246,  244,  248,
      255,  240,  257,  242,  241,  258,  259,  260,  247,  250,
      262,  264,  265,  266,  253,  255,  267,  273,  268,  269,
      272,  258,  257,  271,  270,  263,  261,  256,  259,  266,
      254,  260,  252,  251,  245,  239,  230,  262,  227,  265,
      264,  226,  223,  222,  220,  267,  268,  269,  276,  276,
      276,  277,  277,  277,  278,  278,  217,  216,  208,  206,
      195,  194,  182,  179,  168,  165,  162,  152,  151,  146,

      117,  107,  105,  102,   96,   85,   81,   61,   58,   57,
       56,   30,   28,   27,   26,    9,    8,    7,    3,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dynamic/tools/sledscanner.l"
#define INITIAL 0
/*
 * Copyright (C) 2001, Sun Microsystems, Inc
 *
 * See the file "LICENSE.TERMS" for information on usage and
 * redistribution of this file, and for a DISCLAIMER OF ALL
 * WARRANTIES.
 *
 */
#line 12 "dynamic/tools/sledscanner.l"
#include "sledtree.h"
#include "sledparser.h"
#define yywrap() 1

int yylineno = 1;
const char *yyfilename = NULL;
bool yyNewLineHack = false;
#line 596 "dynamic/tools/sledscanner.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 20 "dynamic/tools/sledscanner.l"


#line 750 "dynamic/tools/sledscanner.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 276 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 520 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 23 "dynamic/tools/sledscanner.l"
case 2:
#line 24 "dynamic/tools/sledscanner.l"
case 3:
#line 25 "dynamic/tools/sledscanner.l"
case 4:
#line 26 "dynamic/tools/sledscanner.l"
case 5:
#line 27 "dynamic/tools/sledscanner.l"
case 6:
#line 28 "dynamic/tools/sledscanner.l"
case 7:
#line 29 "dynamic/tools/sledscanner.l"
case 8:
#line 30 "dynamic/tools/sledscanner.l"
case 9:
#line 31 "dynamic/tools/sledscanner.l"
case 10:
#line 32 "dynamic/tools/sledscanner.l"
case 11:
#line 33 "dynamic/tools/sledscanner.l"
case 12:
#line 34 "dynamic/tools/sledscanner.l"
case 13:
#line 35 "dynamic/tools/sledscanner.l"
case 14:
#line 36 "dynamic/tools/sledscanner.l"
case 15:
#line 37 "dynamic/tools/sledscanner.l"
case 16:
#line 38 "dynamic/tools/sledscanner.l"
case 17:
#line 39 "dynamic/tools/sledscanner.l"
case 18:
#line 40 "dynamic/tools/sledscanner.l"
case 19:
#line 41 "dynamic/tools/sledscanner.l"
case 20:
#line 42 "dynamic/tools/sledscanner.l"
case 21:
#line 43 "dynamic/tools/sledscanner.l"
case 22:
#line 44 "dynamic/tools/sledscanner.l"
case 23:
#line 45 "dynamic/tools/sledscanner.l"
case 24:
#line 46 "dynamic/tools/sledscanner.l"
case 25:
YY_RULE_SETUP
#line 46 "dynamic/tools/sledscanner.l"
{ yylval.ch = yytext[0]; return yytext[0]; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "dynamic/tools/sledscanner.l"
{ return LEQUAL; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "dynamic/tools/sledscanner.l"
{ return NEQUAL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "dynamic/tools/sledscanner.l"
{ return ELLIPSIS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "dynamic/tools/sledscanner.l"
{ return RARROW; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "dynamic/tools/sledscanner.l"
{ return GEQUAL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "dynamic/tools/sledscanner.l"
{ return ADDRESS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "dynamic/tools/sledscanner.l"
{ return ANY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "dynamic/tools/sledscanner.l"
{ return ASSEMBLY; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "dynamic/tools/sledscanner.l"
{ return BIT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "dynamic/tools/sledscanner.l"
{ return CHECKED; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "dynamic/tools/sledscanner.l"
{ return COLUMNS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "dynamic/tools/sledscanner.l"
{ return COMPONENT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "dynamic/tools/sledscanner.l"
{ return CONSTRUCTORS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "dynamic/tools/sledscanner.l"
{ return DISCARD; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "dynamic/tools/sledscanner.l"
{ return ELSE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "dynamic/tools/sledscanner.l"
{ return EPSILON; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "dynamic/tools/sledscanner.l"
{ return FETCH; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "dynamic/tools/sledscanner.l"
{ return FIELD; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "dynamic/tools/sledscanner.l"
{ return FIELDINFO; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "dynamic/tools/sledscanner.l"
{ return FIELDS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "dynamic/tools/sledscanner.l"
{ return FOR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "dynamic/tools/sledscanner.l"
{ return GUARANTEED; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "dynamic/tools/sledscanner.l"
{ return IS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "dynamic/tools/sledscanner.l"
{ return KEEP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "dynamic/tools/sledscanner.l"
{ return MOST; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "dynamic/tools/sledscanner.l"
{ return NAMES; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "dynamic/tools/sledscanner.l"
{ return OF; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "dynamic/tools/sledscanner.l"
{ return OPCODE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "dynamic/tools/sledscanner.l"
{ return OPERAND; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "dynamic/tools/sledscanner.l"
{ return OTHERWISE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "dynamic/tools/sledscanner.l"
{ return PATTERNS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "dynamic/tools/sledscanner.l"
{ return PCUNITBITS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "dynamic/tools/sledscanner.l"
{ return PLACEHOLDER; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "dynamic/tools/sledscanner.l"
{ return RELOCATABLE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "dynamic/tools/sledscanner.l"
{ return SIGNIFICANT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "dynamic/tools/sledscanner.l"
{ return SOME; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "dynamic/tools/sledscanner.l"
{ return SPARSE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "dynamic/tools/sledscanner.l"
{ return SYNTAX; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "dynamic/tools/sledscanner.l"
{ return TO; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "dynamic/tools/sledscanner.l"
{ return TYPE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "dynamic/tools/sledscanner.l"
{ return UNCHECKED; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "dynamic/tools/sledscanner.l"
{ return USING; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "dynamic/tools/sledscanner.l"
{ return WHEN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "dynamic/tools/sledscanner.l"
{ return WHICH; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "dynamic/tools/sledscanner.l"
{ return WORDSIZE; }
	YY_BREAK
case 71:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 93 "dynamic/tools/sledscanner.l"

	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "dynamic/tools/sledscanner.l"
{ 
		  string *str = new string(yytext);
		  yylval.id = symtab.lookup(*str);
		  if( yylval.id == NULL ) {
		      yylval.str = str;
		      return IDENT;
		  }
		  switch( yylval.id->getKind() ) {
		      case FIELD: return FIELDIDENT;
		      case RELOC: return RELOCIDENT;
		      case PATTERN: return PATTERNIDENT;
		      case OPERAND: return PATTERNIDENT;
                      default: assert(0);
		  }		  
		  return IDENT; 
		}
	YY_BREAK
case 73:
#line 111 "dynamic/tools/sledscanner.l"
case 74:
YY_RULE_SETUP
#line 111 "dynamic/tools/sledscanner.l"
{ yylval.i = strtol( yytext, NULL, 0 ); return INTEGER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "dynamic/tools/sledscanner.l"
{ yylval.str = new string(yytext+1,strlen(yytext)-2); return STRING; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 114 "dynamic/tools/sledscanner.l"
{
                  yylval.str = new string(yytext, strlen(yytext)-1);
		  return LABEL;
		}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "dynamic/tools/sledscanner.l"
{ if( yyNewLineHack ){ yylval.ch = ' '; return ' '; } }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "dynamic/tools/sledscanner.l"
{ yylineno++; if( yyNewLineHack ) return NEWLINE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 121 "dynamic/tools/sledscanner.l"

	YY_BREAK
case 80:
YY_RULE_SETUP
#line 122 "dynamic/tools/sledscanner.l"
ECHO;
	YY_BREAK
#line 1179 "dynamic/tools/sledscanner.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 276 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 276 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 275);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 122 "dynamic/tools/sledscanner.l"

